### ISSUE TITLE
Should/could it parallelise reduce()?

### ISSUE THREAD

**Issue by FCO** [lizmat/ParaSeq#1]

**Comment by lizmat** [comment]
Good point...  I completely forgot about `reduce`!  :-)

**Comment by lizmat** [comment]
Ok, so to get `reduce` working I guess we need to make sure that the *order* of the values in the source iterator does not matter.

Can we guarantee that for any given `Callable`?

Or do we say: DIHWIDT if the order *did* matter.

In any case, this would require a post-processing iterator step in this case, re-applying the produced values of each batch.  Also need to make sure that each batch has at least 2 elements  :-)

**Comment by FCO** [comment]
Isn't it enough to just make it clear on documentation?

**Comment by lizmat** [comment]
Added support for `.reduce`, `.sum` and `.join` in version 0.03, now in the ecosystem

**Comment by lizmat** [comment]
So done.
