### ISSUE TITLE
Would it make sense to any method retuning seq to be a ParaSeq?

### ISSUE THREAD

**Issue by FCO** [lizmat/ParaSeq#2]
Sorry for not testing it (I only read the code on my phone) but it seems head, tail (and other methods returning a Seq) returns a Seq and not a ParaSeq. Would it make sense to return a ParaSeq?

**Comment by lizmat** [comment]
`head` and `tail` without arguments are what I call an endpoint: they produce a single value, and it doesn't make sense to make that a `Seq`: in core, they don't either.

`head` and `tail` *with* arguments, return a `ParaSeq`.

Does that answer your question?  If it does, then please close this issue  :-)

**Comment by FCO** [comment]
Yes, it does... it seems I have misread that, sorry. Thanks for your answer
